def distinct_powers():
	"""
	Question: Consider all integer combinations of a^b  for 2<=a<5 and 2<=b<5.
	If the are then placed in numerical order, with any repeats removed, we get
	the following sequence of 15 distinct terms.
	How many distinct terms are in the sequence generated by a^b for 2<=a<=100 and 2<=b<=100?
	"""
	results = []
	for a in range(2, 101):
		for b in range(2, 101):
			result = a**b
			if result not in results:
				results.append(result)
	return len(results)

if __name__ == "__main__":
	print(distinct_powers())
