import math

def triangular_pentagonal_hexagonal():
	"""
	Question: Triangluar, pentagonal, and hexagonal numbers are generated by the
	following formulae:
		Triangle: Tn = n(n+1) /2
		Pentagonal: Pn = n(3n-1)/2
		Hexagonal: Hn = n(2n-1)
	It can be verified that T285 = P165 = H143 = 40755
	Find the next triangle number that is also pentagonal and hexagonal
	"""
	n = 286
	while True:
		Tn = n * (n + 1) // 2
		if is_pentagonal(Tn) and is_hexagonal(Tn):
			return Tn
		n += 1

def is_pentagonal(num):
	"""Check if a number is a pentagonal number."""
	n = (math.sqrt(24 * num + 1) + 1) / 6
	return n.is_integer()

def is_hexagonal(num):
	"""Check if a number is a hexagonal number."""
	n = (math.sqrt(8 * num + 1) + 1) / 4
	return n.is_integer()


if __name__ == "__main__":
	print(triangular_pentagonal_hexagonal())
